[package]
name = "ifstat-rs"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
chrono  = { version = "0.4.22", features = ["serde"] }
clap  = { version = "4.0.22", features = ["derive"] }
env_logger = "0.9.3"
log = "0.4.17"
serde  = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
